"""Models package for GeoAPI."""

# Core OGC models (shared types like Link, GeometryType)
from geoapi.models.ogc import (
    Collection,
    CollectionsResponse,
    Conformance,
    Extent,
    Feature,
    FeatureCollection,
    GeometryType,
    HealthCheck,
    LandingPage,
    Link,
    QueryableProperty,
    Queryables,
    SpatialExtent,
    StyleJSON,
    TileJSON,
    TileMatrixSetItem,
    TileMatrixSetsResponse,
    TileSet,
)

# OGC API Processes models (imports Link, GeometryType from ogc)
from geoapi.models.processes import (
    OGC_EXCEPTION_INVALID_PARAMETER,
    OGC_EXCEPTION_NO_SUCH_JOB,
    OGC_EXCEPTION_NO_SUCH_PROCESS,
    OGC_EXCEPTION_RESULT_NOT_READY,
    ConformanceDeclaration,
    ExecuteRequest,
    InputDescription,
    JobControlOptions,
    JobList,
    Metadata,
    OGCException,
    OutputDescription,
    ProcessDescription,
    ProcessList,
    ProcessSummary,
    ResponseType,
    StatusCode,
    StatusInfo,
    TransmissionMode,
)

__all__ = [
    # OGC Core Models
    "Collection",
    "CollectionsResponse",
    "Conformance",
    "Extent",
    "Feature",
    "FeatureCollection",
    "GeometryType",
    "HealthCheck",
    "LandingPage",
    "Link",
    "Queryables",
    "QueryableProperty",
    "SpatialExtent",
    "StyleJSON",
    "TileJSON",
    "TileMatrixSetItem",
    "TileMatrixSetsResponse",
    "TileSet",
    # Processes Models
    "ConformanceDeclaration",
    "ExecuteRequest",
    "InputDescription",
    "JobControlOptions",
    "JobList",
    "Metadata",
    "OGCException",
    "OGC_EXCEPTION_INVALID_PARAMETER",
    "OGC_EXCEPTION_NO_SUCH_JOB",
    "OGC_EXCEPTION_NO_SUCH_PROCESS",
    "OGC_EXCEPTION_RESULT_NOT_READY",
    "OutputDescription",
    "ProcessDescription",
    "ProcessList",
    "ProcessSummary",
    "ResponseType",
    "StatusCode",
    "StatusInfo",
    "TransmissionMode",
]
