"""Models package for GeoAPI."""

from goatlib.analysis.statistics import (
    AreaOperation,
    ClassBreakMethod,
    SortOrder,
    UniqueValue,
)

from geoapi.models.ogc import (
    Collection,
    CollectionsResponse,
    Conformance,
    Extent,
    Feature,
    FeatureCollection,
    GeometryType,
    HealthCheck,
    LandingPage,
    Link,
    QueryableProperty,
    Queryables,
    SpatialExtent,
    StyleJSON,
    TileJSON,
    TileMatrixSetItem,
    TileMatrixSetsResponse,
    TileSet,
)
from geoapi.models.processes import (
    AreaStatisticsInput,
    AreaStatisticsOutput,
    ClassBreaksInput,
    ClassBreaksOutput,
    ExecuteRequest,
    FeatureCountInput,
    FeatureCountOutput,
    InputDescription,
    JobControlOptions,
    JobList,
    OutputDefinition,
    OutputDescription,
    ProcessDescription,
    ProcessList,
    ProcessSummary,
    ResponseType,
    StatusCode,
    StatusInfo,
    TransmissionMode,
    UniqueValuesInput,
    UniqueValuesOutput,
)

__all__ = [
    # OGC Models
    "Collection",
    "CollectionsResponse",
    "Conformance",
    "Extent",
    "Feature",
    "FeatureCollection",
    "GeometryType",
    "HealthCheck",
    "LandingPage",
    "Link",
    "Queryables",
    "QueryableProperty",
    "SpatialExtent",
    "StyleJSON",
    "TileJSON",
    "TileMatrixSetItem",
    "TileMatrixSetsResponse",
    "TileSet",
    # Process Models
    "AreaStatisticsInput",
    "AreaStatisticsOutput",
    "ClassBreaksInput",
    "ClassBreaksOutput",
    "ExecuteRequest",
    "FeatureCountInput",
    "FeatureCountOutput",
    "InputDescription",
    "JobControlOptions",
    "JobList",
    "OutputDefinition",
    "OutputDescription",
    "ProcessDescription",
    "ProcessList",
    "ProcessSummary",
    "ResponseType",
    "StatusCode",
    "StatusInfo",
    "TransmissionMode",
    "UniqueValue",
    "UniqueValuesInput",
    "UniqueValuesOutput",
    # Enums from goatlib (re-exported for convenience)
    "AreaOperation",
    "ClassBreakMethod",
    "SortOrder",
]
