/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'GetJobAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { jobId: string; status: string; tool_name?: string; output_layer_id?: string; feature_count?: number; error?: string }> | ApiResponse<404, { error: string }>, never>
    'AnalysisAPI': ApiRouteHandler<{ user_id: string; input_layer_id: string; overlay_layer_id?: string; input_filter?: string; overlay_filter?: string; output_layer_id?: string; output_crs?: string }, ApiResponse<200, { message: string; status: string; jobId: string; tool_name: string; output_layer_id: string }> | ApiResponse<400, { error: string }>, { topic: 'analysis-requested'; data: { tool_name: 'clip'; jobId: string; timestamp: string; user_id: string; output_layer_id?: string } }>
    'ProcessAnalysis': EventHandler<{ tool_name: 'clip'; jobId: string; timestamp: string; user_id: string; output_layer_id?: string }, { topic: 'analysis-completed'; data: { jobId: string; tool_name: string; status: string; output_layer_id?: string | unknown; feature_count?: unknown | unknown; geometry_type?: string | unknown; error?: string | unknown; processedAt: string } } | { topic: 'analysis-failed'; data: { jobId: string; tool_name: string; status: string; output_layer_id?: string | unknown; feature_count?: unknown | unknown; geometry_type?: string | unknown; error?: string | unknown; processedAt: string } }>
    'LogAnalysisResult': EventHandler<{ jobId: string; tool_name: string; status: string; output_layer_id?: string | unknown; feature_count?: unknown | unknown; geometry_type?: string | unknown; error?: string | unknown; processedAt: string }, never>
    'ListToolsPython': ApiRouteHandler<Record<string, unknown>, unknown, never>
  }
    
}