networks:
  proxy:
    name: goat

services:
  rabbitmq:
    image: rabbitmq:4.0.3-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      proxy:

  redis:
    image: redis:7.4.1-alpine
    command: redis-server --maxmemory 100mb --maxmemory-policy allkeys-lru
    networks:
      proxy:

  # Windmill Server - API, UI, scheduler
  windmill-server:
    image: ghcr.io/windmill-labs/windmill:main
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_SERVER}:5432/windmill?sslmode=disable
      MODE: server
      BASE_URL: http://localhost:8100
      SUPERADMIN_EMAIL: dev@plan4better.de
      SUPERADMIN_PASSWORD: changeme
    ports:
      - 8110:8000
    networks:
      proxy:

  # Windmill Worker - executes scripts
  windmill-worker:
    image: ghcr.io/windmill-labs/windmill:main
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_SERVER}:5432/windmill?sslmode=disable
      MODE: worker
      WORKER_GROUP: default
      # Use native Python (no venv) so PYTHONPATH and mounted volumes work
      WORKER_TAGS: python3
      DISABLE_NSJAIL: "true"
      # Tool environment variables
      POSTGRES_SERVER: ${POSTGRES_SERVER}
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: goat
      POSTGRES_DATABASE_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_SERVER}:5432/goat
      DUCKLAKE_DATA_DIR: /app/data/ducklake
      DUCKLAKE_CATALOG_SCHEMA: ducklake
      # S3 settings for layer imports
      S3_PROVIDER: ${S3_PROVIDER:-hetzner}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      S3_REGION_NAME: ${S3_REGION_NAME:-${S3_REGION:-us-east-1}}
      # Add goatlib to Python path
      PYTHONPATH: /app/workspace/packages/python/goatlib/src
    networks:
      proxy:
    # Mount entire workspace so scripts can access goatlib and deps
    volumes:
      - ../:/app/workspace:ro
      - ../data/ducklake:/app/data/ducklake
    depends_on:
      - windmill-server

  goat-dev:
    depends_on:
      - rabbitmq
      - redis
      - windmill-server
      - windmill-worker
    build:
      dockerfile: Dockerfile
    container_name: goat-dev
    volumes:
      - ../:/app
    networks:
      proxy:
