services:
  demo:
  tms:
    use_grid_names: true
    # origin for /tiles service
    origin: "nw"
  kml:
    use_grid_names: true
  wmts:
  wms:
    md:
      title: MapProxy WMS Proxy
      abstract: GOAT Mapproxy configuration.

layers:
  - name: osmStandard
    title: OSM Standard
    sources: [osm_standard_cache]

  - name: osmLight
    title: OSM Light
    sources: [osm_light_cache]

  - name: osmDark
    title: OSM Dark
    sources: [osm_dark_cache]

  - name: mapboxStreets
    title: Mapbox Streets
    sources: [mapbox_streets_cache]

  - name: publicTransport
    title: Public Transport
    sources: [public_transport_cache]

  - name: bingAerial
    title: Bing Aerial
    sources: [bing_aerial_cache]

caches:
  osm_standard_cache:
    grids: [webmercator]
    sources: [osm_standard]

  osm_light_cache:
    grids: [webmercator]
    sources: [osm_light]

  osm_dark_cache:
    grids: [webmercator]
    sources: [osm_dark]

  mapbox_streets_cache:
    grids: [webmercator]
    sources: [mapbox_streets]

  public_transport_cache:
    grids: [webmercator]
    sources: [public_transport]

  bing_aerial_cache:
    grids: [webmercator]
    sources: [bing_aerial]

sources:
  osm_standard:
    type: tile
    grid: GLOBAL_WEBMERCATOR
    url: http://a.tile.openstreetmap.org/%(z)s/%(x)s/%(y)s.png

  osm_light:
    type: tile
    grid: GLOBAL_WEBMERCATOR
    url: http://a.basemaps.cartocdn.com/light_all/%(z)s/%(x)s/%(y)s.png

  osm_dark:
    type: tile
    grid: GLOBAL_WEBMERCATOR
    url: http://a.basemaps.cartocdn.com/dark_all/%(z)s/%(x)s/%(y)s.png

  mapbox_streets:
    type: tile
    grid: GLOBAL_WEBMERCATOR
    url: https://api.mapbox.com/styles/v1/mapbox/streets-v10/tiles/256/%(z)s/%(x)s/%(y)s?access_token=pk.eyJ1IjoiZWxpYXNwYWphcmVzIiwiYSI6ImNqOW1scnVyOTRxcWwzMm5yYWhta2N2cXcifQ.aDCgidtC9cjf_O75frn9lA

  public_transport:
    type: tile
    grid: GLOBAL_WEBMERCATOR
    url: https://tileserver.memomaps.de/tilegen/%(z)s/%(x)s/%(y)s.png

  bing_aerial:
    type: tile
    grid: GLOBAL_WEBMERCATOR
    url: http://tiles.virtualearth.net/tiles/a%(quadkey)s.png?g=587&mkt=en-US&n=z&key=Avv4X-3gpZJQ_Ln2eAilMZ8qNI4Y6UtspyNxgIzoCSZC26xi_aXb3AiaXnutPPjH

grids:
  webmercator:
    base: GLOBAL_WEBMERCATOR

globals:
  image:
    resampling_method: nearest
