"""add report_layout table

Revision ID: 44c27ff7ceb6
Revises: 73d0531e12fd
Create Date: 2025-12-10 15:44:35.526290

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44c27ff7ceb6'
down_revision = '73d0531e12fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_layout',
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('to_char(CURRENT_TIMESTAMP AT TIME ZONE \'UTC\', \'YYYY-MM-DD"T"HH24:MI:SSOF\')::timestamptz'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_predefined', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['customer.project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='customer'
    )
    op.create_index(op.f('ix_customer_report_layout_project_id'), 'report_layout', ['project_id'], unique=False, schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_report_layout_project_id'), table_name='report_layout', schema='customer')
    op.drop_table('report_layout', schema='customer')
    # ### end Alembic commands ###
