"""empty message

Revision ID: 606f91f79a4e
Revises:
Create Date: 2025-11-12 09:42:02.992164

"""

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "606f91f79a4e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    op.execute("CREATE SCHEMA IF NOT EXISTS accounts;")
    op.execute("CREATE SCHEMA IF NOT EXISTS basic;")
    op.execute("CREATE SCHEMA IF NOT EXISTS user_data;")
    op.execute("CREATE SCHEMA IF NOT EXISTS temporal;")
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis;")
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis_raster;")
    op.execute("CREATE EXTENSION IF NOT EXISTS h3;")
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    op.execute('CREATE EXTENSION IF NOT EXISTS "btree_gist";')
    op.execute('CREATE EXTENSION IF NOT EXISTS "fuzzystrmatch";')
    op.execute('CREATE EXTENSION IF NOT EXISTS "hstore";')
    op.execute('CREATE EXTENSION IF NOT EXISTS "citus";')
    op.execute('CREATE EXTENSION IF NOT EXISTS "citus_columnar";')
    op.execute('CREATE EXTENSION IF NOT EXISTS "postgres_fdw";')
    op.execute('CREATE EXTENSION IF NOT EXISTS "intarray";')
    # Check if accounts.user exists, and create a minimal version if not
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.tables
            WHERE table_schema = 'accounts' AND table_name = 'user'
        ) THEN
            CREATE TABLE accounts."user" (
                id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
                firstname TEXT NULL,
                lastname TEXT NULL,
                avatar TEXT NULL
            );
        END IF;
    END
    $$;
    """)
    # Check if accounts.organization exists, and create a minimal version if not
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.tables
            WHERE table_schema = 'accounts' AND table_name = 'organization'
        ) THEN
            CREATE TABLE accounts.organization (
                id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
                name TEXT NOT NULL,
                avatar TEXT NULL,
                created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
                updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL
            );
        END IF;
    END
    $$;
    """)
    # Check if accounts.role exists, and create a minimal version if not
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.tables
            WHERE table_schema = 'accounts' AND table_name = 'role'
        ) THEN
            CREATE TABLE accounts.role (
                id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
                name TEXT NOT NULL,
                created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
                updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL
            );
        END IF;
    END
    $$;
    """)
    # Check accounts.team exists, and create a minimal version if not
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.tables
            WHERE table_schema = 'accounts' AND table_name = 'team'
        ) THEN
            CREATE TABLE accounts.team (
                id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
                name TEXT NOT NULL,
                avatar TEXT NULL,
                created_at timestamp DEFAULT CURRENT_TIMESTAMP NULL,
                updated_at timestamp DEFAULT CURRENT_TIMESTAMP NULL
            );
        END IF;
    END
    $$;
    """)

    op.execute("create schema if not exists customer;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_store",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SSOF')::timestamptz"
            ),
            nullable=False,
        ),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="customer",
    )
    op.create_table(
        "status",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("status", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="customer",
    )
    op.create_table(
        "system_task",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("last_run", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="customer",
    )
    op.create_table(
        "folder",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SSOF')::timestamptz"
            ),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["accounts.user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="customer",
    )
    op.create_table(
        "job",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SSOF')::timestamptz"
            ),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("layer_ids", sa.ARRAY(sa.UUID()), nullable=True),
        sa.Column("status", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status_simple", sa.Text(), nullable=False),
        sa.Column("msg_simple", sa.Text(), nullable=True),
        sa.Column("read", sa.Boolean(), server_default="False", nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["accounts.user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="customer",
    )
    op.create_index(
        op.f("ix_customer_job_layer_ids"),
        "job",
        ["layer_ids"],
        unique=False,
        schema="customer",
    )
    op.create_index(
        op.f("ix_customer_job_status_simple"),
        "job",
        ["status_simple"],
        unique=False,
        schema="customer",
    )
    op.create_table(
        "system_setting",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SSOF')::timestamptz"
            ),
            nullable=False,
        ),
        sa.Column("client_theme", sa.Text(), nullable=False),
        sa.Column("preferred_language", sa.Text(), nullable=False),
        sa.Column("unit", sa.Text(), nullable=False),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["accounts.user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="customer",
    )
    op.create_table(
        "uploaded_asset",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SSOF')::timestamptz"
            ),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("s3_key", sa.Text(), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=True),
        sa.Column("category", sa.String(length=100), nullable=True),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column(
            "asset_type", sa.Enum("image", "icon", name="assettype"), nullable=False
        ),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["accounts.user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("s3_key"),
        schema="customer",
    )
    op.create_table(
        "layer",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SSOF')::timestamptz"
            ),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("lineage", sa.Text(), nullable=True),
        sa.Column("positional_accuracy", sa.Text(), nullable=True),
        sa.Column("attribute_accuracy", sa.Text(), nullable=True),
        sa.Column("completeness", sa.Text(), nullable=True),
        sa.Column("geographical_code", sa.Text(), nullable=True),
        sa.Column("language_code", sa.Text(), nullable=True),
        sa.Column("distributor_name", sa.Text(), nullable=True),
        sa.Column("distributor_email", sa.Text(), nullable=True),
        sa.Column("distribution_url", sa.Text(), nullable=True),
        sa.Column("license", sa.Text(), nullable=True),
        sa.Column("attribution", sa.Text(), nullable=True),
        sa.Column("data_reference_year", sa.Integer(), nullable=True),
        sa.Column("data_category", sa.Text(), nullable=True),
        sa.Column("in_catalog", sa.Boolean(), server_default="False", nullable=False),
        sa.Column("thumbnail_url", sa.Text(), nullable=True),
        sa.Column("tags", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("folder_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("data_store_id", sa.UUID(), nullable=True),
        sa.Column(
            "extent",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("properties", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "other_properties", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("data_type", sa.Text(), nullable=True),
        sa.Column("tool_type", sa.Text(), nullable=True),
        sa.Column("job_id", sa.UUID(), nullable=True),
        sa.Column("feature_layer_type", sa.Text(), nullable=True),
        sa.Column("feature_layer_geometry_type", sa.Text(), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column(
            "attribute_mapping", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("upload_reference_system", sa.Integer(), nullable=True),
        sa.Column("upload_file_type", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["data_store_id"],
            ["customer.data_store.id"],
        ),
        sa.ForeignKeyConstraint(
            ["folder_id"], ["customer.folder.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["accounts.user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="customer",
    )
    op.create_table(
        "project",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SSOF')::timestamptz"
            ),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("folder_id", sa.UUID(), nullable=False),
        sa.Column("active_scenario_id", sa.UUID(), nullable=True),
        sa.Column("layer_order", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("basemap", sa.Text(), nullable=True),
        sa.Column("thumbnail_url", sa.Text(), nullable=True),
        sa.Column("max_extent", sa.ARRAY(sa.Float()), nullable=True),
        sa.Column(
            "builder_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("tags", sa.ARRAY(sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["folder_id"], ["customer.folder.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["accounts.user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="customer",
    )
    op.create_table(
        "layer_project",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SSOF')::timestamptz"
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("group", sa.Text(), nullable=True),
        sa.Column("layer_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("properties", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "other_properties", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("query", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("charts", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["layer_id"], ["customer.layer.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["customer.project.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="customer",
    )
    op.create_table(
        "project_public",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SSOF')::timestamptz"
            ),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("password", sa.Text(), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["customer.project.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="customer",
    )
    op.create_index(
        op.f("ix_customer_project_public_id"),
        "project_public",
        ["id"],
        unique=False,
        schema="customer",
    )
    op.create_table(
        "scenario",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SSOF')::timestamptz"
            ),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"], ["customer.project.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["accounts.user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="customer",
    )
    op.create_table(
        "user_project",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SSOF')::timestamptz"
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column(
            "initial_view_state",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["customer.project.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["accounts.user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="customer",
    )
    op.create_table(
        "scenario_feature",
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                srid=4326,
                spatial_index=False,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.Column("integer_attr1", sa.Integer(), nullable=True),
        sa.Column("float_attr1", sa.Float(), nullable=True),
        sa.Column("text_attr1", sa.Text(), nullable=True),
        sa.Column("integer_attr2", sa.Integer(), nullable=True),
        sa.Column("float_attr2", sa.Float(), nullable=True),
        sa.Column("text_attr2", sa.Text(), nullable=True),
        sa.Column("integer_attr3", sa.Integer(), nullable=True),
        sa.Column("float_attr3", sa.Float(), nullable=True),
        sa.Column("text_attr3", sa.Text(), nullable=True),
        sa.Column("integer_attr4", sa.Integer(), nullable=True),
        sa.Column("float_attr4", sa.Float(), nullable=True),
        sa.Column("text_attr4", sa.Text(), nullable=True),
        sa.Column("integer_attr5", sa.Integer(), nullable=True),
        sa.Column("float_attr5", sa.Float(), nullable=True),
        sa.Column("text_attr5", sa.Text(), nullable=True),
        sa.Column("integer_attr6", sa.Integer(), nullable=True),
        sa.Column("float_attr6", sa.Float(), nullable=True),
        sa.Column("text_attr6", sa.Text(), nullable=True),
        sa.Column("integer_attr7", sa.Integer(), nullable=True),
        sa.Column("float_attr7", sa.Float(), nullable=True),
        sa.Column("text_attr7", sa.Text(), nullable=True),
        sa.Column("integer_attr8", sa.Integer(), nullable=True),
        sa.Column("float_attr8", sa.Float(), nullable=True),
        sa.Column("text_attr8", sa.Text(), nullable=True),
        sa.Column("integer_attr9", sa.Integer(), nullable=True),
        sa.Column("float_attr9", sa.Float(), nullable=True),
        sa.Column("text_attr9", sa.Text(), nullable=True),
        sa.Column("integer_attr10", sa.Integer(), nullable=True),
        sa.Column("float_attr10", sa.Float(), nullable=True),
        sa.Column("text_attr10", sa.Text(), nullable=True),
        sa.Column("integer_attr11", sa.Integer(), nullable=True),
        sa.Column("float_attr11", sa.Float(), nullable=True),
        sa.Column("text_attr11", sa.Text(), nullable=True),
        sa.Column("integer_attr12", sa.Integer(), nullable=True),
        sa.Column("float_attr12", sa.Float(), nullable=True),
        sa.Column("text_attr12", sa.Text(), nullable=True),
        sa.Column("integer_attr13", sa.Integer(), nullable=True),
        sa.Column("float_attr13", sa.Float(), nullable=True),
        sa.Column("text_attr13", sa.Text(), nullable=True),
        sa.Column("integer_attr14", sa.Integer(), nullable=True),
        sa.Column("float_attr14", sa.Float(), nullable=True),
        sa.Column("text_attr14", sa.Text(), nullable=True),
        sa.Column("integer_attr15", sa.Integer(), nullable=True),
        sa.Column("float_attr15", sa.Float(), nullable=True),
        sa.Column("text_attr15", sa.Text(), nullable=True),
        sa.Column("integer_attr16", sa.Integer(), nullable=True),
        sa.Column("float_attr16", sa.Float(), nullable=True),
        sa.Column("text_attr16", sa.Text(), nullable=True),
        sa.Column("integer_attr17", sa.Integer(), nullable=True),
        sa.Column("float_attr17", sa.Float(), nullable=True),
        sa.Column("text_attr17", sa.Text(), nullable=True),
        sa.Column("integer_attr18", sa.Integer(), nullable=True),
        sa.Column("float_attr18", sa.Float(), nullable=True),
        sa.Column("text_attr18", sa.Text(), nullable=True),
        sa.Column("integer_attr19", sa.Integer(), nullable=True),
        sa.Column("float_attr19", sa.Float(), nullable=True),
        sa.Column("text_attr19", sa.Text(), nullable=True),
        sa.Column("integer_attr20", sa.Integer(), nullable=True),
        sa.Column("float_attr20", sa.Float(), nullable=True),
        sa.Column("text_attr20", sa.Text(), nullable=True),
        sa.Column("integer_attr21", sa.Integer(), nullable=True),
        sa.Column("float_attr21", sa.Float(), nullable=True),
        sa.Column("text_attr21", sa.Text(), nullable=True),
        sa.Column("integer_attr22", sa.Integer(), nullable=True),
        sa.Column("float_attr22", sa.Float(), nullable=True),
        sa.Column("text_attr22", sa.Text(), nullable=True),
        sa.Column("integer_attr23", sa.Integer(), nullable=True),
        sa.Column("float_attr23", sa.Float(), nullable=True),
        sa.Column("text_attr23", sa.Text(), nullable=True),
        sa.Column("integer_attr24", sa.Integer(), nullable=True),
        sa.Column("float_attr24", sa.Float(), nullable=True),
        sa.Column("text_attr24", sa.Text(), nullable=True),
        sa.Column("integer_attr25", sa.Integer(), nullable=True),
        sa.Column("float_attr25", sa.Float(), nullable=True),
        sa.Column("text_attr25", sa.Text(), nullable=True),
        sa.Column("bigint_attr1", sa.BigInteger(), nullable=True),
        sa.Column("bigint_attr2", sa.BigInteger(), nullable=True),
        sa.Column("bigint_attr3", sa.BigInteger(), nullable=True),
        sa.Column("bigint_attr4", sa.BigInteger(), nullable=True),
        sa.Column("bigint_attr5", sa.BigInteger(), nullable=True),
        sa.Column(
            "jsonb_attr1", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("boolean_attr1", sa.Boolean(), nullable=True),
        sa.Column(
            "jsonb_attr2", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("boolean_attr2", sa.Boolean(), nullable=True),
        sa.Column(
            "jsonb_attr3", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("boolean_attr3", sa.Boolean(), nullable=True),
        sa.Column(
            "jsonb_attr4", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("boolean_attr4", sa.Boolean(), nullable=True),
        sa.Column(
            "jsonb_attr5", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("boolean_attr5", sa.Boolean(), nullable=True),
        sa.Column(
            "jsonb_attr6", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("boolean_attr6", sa.Boolean(), nullable=True),
        sa.Column(
            "jsonb_attr7", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("boolean_attr7", sa.Boolean(), nullable=True),
        sa.Column(
            "jsonb_attr8", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("boolean_attr8", sa.Boolean(), nullable=True),
        sa.Column(
            "jsonb_attr9", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("boolean_attr9", sa.Boolean(), nullable=True),
        sa.Column(
            "jsonb_attr10", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("boolean_attr10", sa.Boolean(), nullable=True),
        sa.Column("arrint_attr1", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("arrfloat_attr1", sa.ARRAY(sa.Float()), nullable=True),
        sa.Column("arrtext_attr1", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("timestamp_attr1", sa.DateTime(), nullable=True),
        sa.Column("arrint_attr2", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("arrfloat_attr2", sa.ARRAY(sa.Float()), nullable=True),
        sa.Column("arrtext_attr2", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("timestamp_attr2", sa.DateTime(), nullable=True),
        sa.Column("arrint_attr3", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("arrfloat_attr3", sa.ARRAY(sa.Float()), nullable=True),
        sa.Column("arrtext_attr3", sa.ARRAY(sa.Text()), nullable=True),
        sa.Column("timestamp_attr3", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SSOF')::timestamptz"
            ),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("feature_id", sa.UUID(), nullable=True),
        sa.Column("layer_project_id", sa.Integer(), nullable=False),
        sa.Column("h3_3", sa.Integer(), nullable=True),
        sa.Column("h3_6", sa.Integer(), nullable=True),
        sa.Column("edit_type", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["layer_project_id"], ["customer.layer_project.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="customer",
    )
    op.create_index(
        "scenario_feature_geom_idx",
        "scenario_feature",
        ["geom"],
        unique=False,
        schema="customer",
        postgresql_using="gist",
    )
    op.create_table(
        "scenario_scenario_feature",
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text(
                "to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD\"T\"HH24:MI:SSOF')::timestamptz"
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("scenario_id", sa.UUID(), nullable=False),
        sa.Column("scenario_feature_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["scenario_feature_id"],
            ["customer.scenario_feature.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["scenario_id"], ["customer.scenario.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", "scenario_id", "scenario_feature_id"),
        schema="customer",
    )
    # check if accounts.user_team exists, and create a minimal version if not
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.tables
            WHERE table_schema = 'accounts' AND table_name = 'user_team'
        ) THEN
            CREATE TABLE accounts.user_team (
                id SERIAL PRIMARY KEY,
                user_id UUID NOT NULL,
                team_id UUID NOT NULL,
                FOREIGN KEY (user_id) REFERENCES accounts."user"(id) ON DELETE CASCADE,
                FOREIGN KEY (team_id) REFERENCES accounts.team(id) ON DELETE CASCADE
            );
        END IF;
    END
    $$;
    """)

    # check if accounts.layer_organization exists, and create a minimal version if not
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.tables
            WHERE table_schema = 'accounts' AND table_name = 'layer_organization'
        ) THEN
            CREATE TABLE accounts.layer_organization (
                id SERIAL PRIMARY KEY,
                layer_id UUID NOT NULL,
                organization_id UUID NOT NULL,
                role_id UUID NOT NULL,
                FOREIGN KEY (role_id) REFERENCES accounts.role(id),
                FOREIGN KEY (layer_id) REFERENCES customer.layer(id) ON DELETE CASCADE,
                FOREIGN KEY (organization_id) REFERENCES accounts.organization(id) ON DELETE CASCADE
            );
        END IF;
    END
    $$;
    """)

    # check if accounts.layer_team exists, and create a minimal version if not
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.tables
            WHERE table_schema = 'accounts' AND table_name = 'layer_team'
        ) THEN
            CREATE TABLE accounts.layer_team (
                id SERIAL PRIMARY KEY,
                team_id UUID NOT NULL,
                layer_id UUID NOT NULL,
                role_id UUID NOT NULL,
                FOREIGN KEY (role_id) REFERENCES accounts.role(id),
                FOREIGN KEY (team_id) REFERENCES accounts.team(id) ON DELETE CASCADE,
                FOREIGN KEY (layer_id) REFERENCES customer.layer(id) ON DELETE CASCADE
            );
        END IF;
    END
    $$;
    """)

    # check if accounts.project_team exists, and create a minimal version if not
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.tables
            WHERE table_schema = 'accounts' AND table_name = 'project_team'
        ) THEN
            CREATE TABLE accounts.project_team (
                id SERIAL PRIMARY KEY,
                team_id UUID NOT NULL,
                project_id UUID NOT NULL,
                role_id UUID NOT NULL,
                FOREIGN KEY (role_id) REFERENCES accounts.role(id),
                FOREIGN KEY (team_id) REFERENCES accounts.team(id) ON DELETE CASCADE,
                FOREIGN KEY (project_id) REFERENCES customer.project(id) ON DELETE CASCADE
            );
        END IF;
    END
    $$;
    """)

    # Check if accounts.project_organization exists, and create a minimal version if not
    op.execute("""
    DO $$
    BEGIN
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.tables
            WHERE table_schema = 'accounts' AND table_name = 'project_organization'
        ) THEN
            CREATE TABLE accounts.project_organization (
                id SERIAL PRIMARY KEY,
                organization_id UUID NOT NULL,
                project_id UUID NOT NULL,
                role_id UUID NOT NULL,
                FOREIGN KEY (role_id) REFERENCES accounts.role(id),
                FOREIGN KEY (organization_id) REFERENCES accounts.organization(id) ON DELETE CASCADE,
                FOREIGN KEY (project_id) REFERENCES customer.project(id) ON DELETE CASCADE
            );
        END IF;
    END
    $$;
    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("scenario_scenario_feature", schema="customer")
    op.drop_index(
        "scenario_feature_geom_idx",
        table_name="scenario_feature",
        schema="customer",
        postgresql_using="gist",
    )
    op.drop_table("scenario_feature", schema="customer")
    op.drop_table("user_project", schema="customer")
    op.drop_table("scenario", schema="customer")
    op.drop_index(
        op.f("ix_customer_project_public_id"),
        table_name="project_public",
        schema="customer",
    )
    op.drop_table("project_public", schema="customer")
    op.drop_table("layer_project", schema="customer")
    op.drop_table("project", schema="customer")
    op.drop_table("layer", schema="customer")
    op.drop_table("uploaded_asset", schema="customer")
    op.drop_table("system_setting", schema="customer")
    op.drop_index(
        op.f("ix_customer_job_status_simple"), table_name="job", schema="customer"
    )
    op.drop_index(
        op.f("ix_customer_job_layer_ids"), table_name="job", schema="customer"
    )
    op.drop_table("job", schema="customer")
    op.drop_table("folder", schema="customer")
    op.drop_table("system_task", schema="customer")
    op.drop_table("status", schema="customer")
    op.drop_table("data_store", schema="customer")

    op.execute("drop schema if exists customer cascade;")
    op.execute("drop schema if exists basic cascade;")
    # ### end Alembic commands ###
