"""update_job_table_indexes

Revision ID: 69a096382fae
Revises: migrate_job_status_ogc
Create Date: 2026-01-11 15:20:40.394054

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel  

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69a096382fae'
down_revision = 'migrate_job_status_ogc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customer_job_layer_ids', table_name='job', schema='customer')
    op.drop_index('ix_customer_job_status_simple', table_name='job', schema='customer')
    op.create_index(op.f('ix_customer_job_status'), 'job', ['status'], unique=False, schema='customer')
    op.drop_column('job', 'layer_ids', schema='customer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('layer_ids', postgresql.ARRAY(sa.UUID()), autoincrement=False, nullable=True), schema='customer')
    op.drop_index(op.f('ix_customer_job_status'), table_name='job', schema='customer')
    op.create_index('ix_customer_job_status_simple', 'job', ['status'], unique=False, schema='customer')
    op.create_index('ix_customer_job_layer_ids', 'job', ['layer_ids'], unique=False, schema='customer')
    # ### end Alembic commands ###
