/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'PrintReportGenerate': EventHandler<{ job_id: string; user_id: string; access_token: string; project_id: string; layout_id: string; format?: string; atlas_page_indices?: Array<unknown> | unknown; timestamp: string }, { topic: 'job.completed'; data: never } | { topic: 'job.failed'; data: never }>
    'LogJobStatus': EventHandler<never, never>
    'LogAnalysisResult': EventHandler<{ jobId: string; tool_name: string; status: string; output_layer_id?: string | unknown; feature_count?: unknown | unknown; geometry_type?: string | unknown; error?: string | unknown; processedAt: string }, never>
    'SwaggerUI': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'OGCConformance': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'OGCLandingPage': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'OpenAPISpec': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'LayerImport': EventHandler<{ job_id: string; user_id: string; layer_id: string; folder_id: string; name: string; description?: string | unknown; tags?: Array<string> | unknown; s3_key?: string | unknown; wfs_url?: string | unknown; wfs_layer_name?: string | unknown; data_type?: string | unknown; other_properties?: Record<string, unknown> | unknown; project_id?: string | unknown }, { topic: 'job.completed'; data: never } | { topic: 'job.failed'; data: never }>
    'LayerDelete': EventHandler<{ job_id: string; user_id: string; layer_id: string }, { topic: 'job.completed'; data: never } | { topic: 'job.failed'; data: never }>
    'LayerUpdate': EventHandler<{ job_id: string; user_id: string; layer_id: string; s3_key?: string | unknown; refresh_wfs?: boolean; wfs_url?: string | unknown; wfs_layer_name?: string | unknown }, { topic: 'job.completed'; data: never } | { topic: 'job.failed'; data: never }>
    'ProcessAnalysis': EventHandler<{ tool_name: 'clip'; jobId: string; timestamp: string; user_id: string; output_layer_id?: string }, { topic: 'analysis-completed'; data: { jobId: string; tool_name: string; status: string; output_layer_id?: string | unknown; feature_count?: unknown | unknown; geometry_type?: string | unknown; error?: string | unknown; processedAt: string } } | { topic: 'analysis-failed'; data: { jobId: string; tool_name: string; status: string; output_layer_id?: string | unknown; feature_count?: unknown | unknown; geometry_type?: string | unknown; error?: string | unknown; processedAt: string } } | { topic: 'job.completed'; data: never } | { topic: 'job.failed'; data: never }>
    'LayerExport': EventHandler<{ job_id: string; user_id: string; layer_id: string; layer_owner_id: string; file_type: string; file_name: string; crs?: string | unknown; query?: string | unknown }, { topic: 'job.completed'; data: never } | { topic: 'job.failed'; data: never }>
    'PrintReportExecute': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'print-requested'; data: { job_id: string; user_id: string; access_token: string; project_id: string; layout_id: string; format?: string; atlas_page_indices?: Array<unknown> | unknown; timestamp: string } }>
  }
    
}